// Generated by https://quicktype.io

export interface Voluntarios {
    voluntarios: Voluntario[];
    pagination:  Pagination;
}

export interface Pagination {
    count: number;
    pages: number;
}

export interface Voluntario {
    id?:             string;
    nombre:         string;
    apellidos:      string;
    contacto:       string;
    disponibilidad: Disponibilidad[];
    isPrecursor:    boolean;
    congregacion:   Congregacion;
    createdAt?:      string;
}

export enum Congregacion {
    ElaNguema = "Ela_Nguema",
    Lampert = "Lampert",
    Sampaka = "Sampaka",
    Timbabe = "Timbabe",
    CampoYaunde = "Campo_Yaunde",
    Frances = "Frances",
    Caracolas = "Caracolas",
    Paraiso = "Paraiso",
    Ingles = "Ingles",
    Fang = "Fang",
    BuenaEsperanza = "Buena_Esperanza",
}

export enum Disponibilidad {
    DomingoT4 = "DomingoT4",
    JuevesT2 = "JuevesT2",
    MartesT1 = "MartesT1",
    MartesT2 = "MartesT2",
}

